name: Build and publish as artifact

on:

  push:

jobs:

  run:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK 17

        uses: actions/setup-java@v3

        with:

          java-version: 17

          distribution: 'temurin'

      - uses: actions/cache@v3

        with:

          path: |

            ~/.gradle/caches

            ~/.gradle/wrapper

          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

          restore-keys: |

            ${{ runner.os }}-gradle-





      - name: Build

        run: ./gradlew build

      - name: Upload artifacts

        uses: actions/upload-artifact@v3

        with:

          name: build-artifacts

          path: |

            Forge/build/libs/ferritecore-*-forge.jar

            Fabric/build/libs/ferritecore-*-fabric.jar
